build:
    tests:
        override:
            -
                command: 'vendor/bin/tester tests -p php -c ./tests/php.ini-unix --coverage build/logs/clover.xml --coverage-src src'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'