language: php

env:
  - NETTE=default
  - NETTE=~2.2.0

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

before_script:
  - php .travis.composer.php
  - composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

script:
  - vendor/bin/tester tests -p php

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'