language: php

env:
  - NETTE=default
  - NETTE=~2.2.0

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" =~ ^hhvm ]; then echo "xdebug.enable = On" >> /etc/hhvm/php.ini; fi;'
  - php .travis.composer.php
  - composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

script:
  - vendor/bin/tester tests -p php -c ./tests/php.ini-unix --coverage build/logs/clover.xml --coverage-src src

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml